/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_prospacecraft_ProspaceCore_ClassProcessor */

#ifndef _Included_net_prospacecraft_ProspaceCore_ClassProcessor
#define _Included_net_prospacecraft_ProspaceCore_ClassProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_prospacecraft_ProspaceCore_ClassProcessor
 * Method:    enableClassProcessor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_prospacecraft_ProspaceCore_ClassProcessor_enableClassProcessor
  (JNIEnv *, jclass);

/*
 * Class:     net_prospacecraft_ProspaceCore_ClassProcessor
 * Method:    disableClassProcessor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_prospacecraft_ProspaceCore_ClassProcessor_disableClassProcessor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
